<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<form action="<?= $variables['purchase']['purchasing']['formAction'] ?>" method="post">

    <div>
        <?= $this->translate('payment-redirect-text') ?> Paygine.
    </div>

    <div>
        <input type="submit" value="<?= $this->translate('pay') ?>" class="button big"/>
    </div>
</form>
<?=$this->render(array(), 'emarket/payment/form-send')?>
